### ISSUE TITLE
Could you explain about your output json file

### ISSUE THREAD

**Issue by yellowjs0304** [chihyaoma/selfmonitoring-agent#1]
Hello~
Thank you for sharing your code :)
I followed your readme scripts.

In the process of training your model  `python tasks/R2R-pano/main.py`, I got results/experiments__val_seen_epoch_num.json files.

But, I can't understand about your json file, correctly. 
Could you explain about it by making a readme file ?

**Comment by chihyaoma** [comment]
Hi, 

Thanks for your interest. Let me know if below answers your question. 

- **instr_id**: id of the instruction currently used for navigation
- **trajectory**: the list of tuple contains the (viewpoints, headings, elevations)
- **distance**: distance to the goal
- **img_attn**: visual grounding attentions
- **ctx_attn**: textual grounding attentions
- **value**: the output of progress monitor, reflecting agent's confidence in completing the navigational instruction
- **viewpoint_idx**: the direction that the agent takes to reach to next viewpoint
- **navigable_idx**: the list of directions that agent can select in the panoramic action space for each step

Many of these recordings are just for visualization purpose. You don't really need them for submitting to the test server.

**Comment by yellowjs0304** [comment]
Thank you for reply.
It is really useful.
