### ISSUE TITLE
Updating links

### ISSUE THREAD

**Issue by guhur** [chihyaoma/selfmonitoring-agent#16]
Hi,

In this repository, the links are broken.

Peter has updated the links for downloading data and image features.
See: https://github.com/peteanderson80/Matterport3DSimulator/commit/dbf728a1bed22dd570c5a7f61c1afb1ee5393c83

**Comment by chihyaoma** [comment]
Hi, 

I just checked. They seem to be working just fine. Can you please let me know which links are broken?

**Comment by guhur** [comment]
Hi,
The JSON are fine. Only the Resnet features are broken:

See:
 https://storage.googleapis.com/bringmeaspoon/img_features/ResNet-152-imagenet.zip

It is now at:

https://www.dropbox.com/s/o57kxh2mn5rkx4o/ResNet-152-imagenet.zip?dl=1

**Comment by chihyaoma** [comment]
Yeah, you are right. I missed that command line in the README. Just fixed it :) Thank you!
