### ISSUE TITLE
Could you share the pre-trained model that you reported in paper?

### ISSUE THREAD

**Issue by yellowjs0304** [chihyaoma/selfmonitoring-agent#2]
Hi, I did your readmescripts.
I did this command,  `CUDA_VISIBLE_DEVICES=0 python tasks/R2R-pano/main.py \
    --exp_name 'cogrounding-selfmonitoring-agent' \
    --batch_size 64 \
    --img_fc_use_angle 1 \
    --img_feat_input_dim 2176 \
    --img_fc_dim 1024 \
    --rnn_hidden_size 512 \
    --eval_every_epochs 5 \
    --use_ignore_index 1 \
    --arch 'self-monitoring' \
    --value_loss_weight 0.5 \
    --monitor_sigmoid 0 \
    --mse_sum 0 \
    --fix_action_ended 0`
but I can't get such performance that you reported in paper.
Excuse, but could you share the pre-trained model that you used?

**Comment by chihyaoma** [comment]
Hi, 

Sure. I will look into that. 

Would you mind sharing what are the results you got in the meantime? Was it a big difference?

**Comment by yellowjs0304** [comment]
Thank you for reply.
I saw the Table 2 in your paper.
I got results after first command(as mentioned above).
- Success Rate on val-seen env 69.6%(epoch : 455)
- Success Rate on val-unseen env 43.04%(epoch : 455)
Maybe I misunderstood your paper, but is this the right result?

**Comment by chihyaoma** [comment]
That specific command is supposed to reproduce the 2nd row in Table 2 in our paper.
Here is the comparison of Table 2 (2nd row) and your results:

SR on val-seen:  63% (ours) vs 69.6% (yours)
SR on val-unseen:  44% (ours) vs 43% (yours)

In short, your reproduced number is much higher on val-seen but slightly lower on val-unseen, which in my opinion seems to be within a reasonable range.

Please let me know if you have other questions.

**Comment by yellowjs0304** [comment]
Thank you so much.
Then, the command (in your readme - Train on synthetic data & finetune on real data) is same with 3nd row (in table2)??

I think I misunderstood about this.
What should i do to get the 8nd row(the best result)??

**Comment by chihyaoma** [comment]
Yes, it will be the same as the 3rd row in Table 2. 

To get the result using beam search (8th row), you need to resume the model trained from both synthetic and real data and perform beam search (I do not have the command for it in the README). 

I however have provided a command for using beam search with a model trained only using real data in the README. This will reproduce the result in the 7th row. I am sure you will be able to adapt the command to reproduce the result in the 8th row.

**Comment by yellowjs0304** [comment]
I got it :)
Thank u for kindly reply~
