### ISSUE TITLE
CPU parallelism

### ISSUE THREAD

**Issue by YicongHong** [chihyaoma/selfmonitoring-agent#4]
Hello Chih-Yao Ma,

I notice that your network achieves multiple CPU core processing for the agent which significantly speed up the training process. Can you tell me which part of your code actually do that? I can't find where you achieve CPU parallelism, but the code is indeed running on multiple cores.

Cheers,
Yicong

**Comment by chihyaoma** [comment]
Hi, 

That's a good question. There is actually no CPU parallelism in my code, but I think the CPU parallelism effect that you observed probably come from the rendering process in the backend. Everything regarding the environment simulator should be pretty much the same when Peter first released the [Matterport3DSimulator](https://github.com/peteanderson80/Matterport3DSimulator), except that I added the panoramic view and action space. 

In February 2019, Peter released several updates on his original repo, including making the environment simulator run far more efficient. If you are interested in making the environment run faster, I would encourage you to check it out as well.

**Comment by YicongHong** [comment]
Thank you so much for your reply!!! :D
