### ISSUE TITLE
Cannot generate /tasks/R2R-pano/result

### ISSUE THREAD

**Issue by Hannah-hh** [chihyaoma/selfmonitoring-agent#6]
Thank you for your sharing your code firstly.

I followed your Readme to run this code. When I executed 'python tasks/R2R-pano/main.py', I could not get '/tasks/R2R-pano/result'.
![2019-05-28 15-08-59屏幕截图](https://user-images.githubusercontent.com/51105211/58459127-402ad000-815d-11e9-8233-affcc410c3c0.png)

Do you know why?
Thank you so much.

**Comment by xiran2018** [comment]
u should create directory “results” manually

**Comment by Hannah-hh** [comment]
I got it.
Thank you for your reply!
