### ISSUE TITLE
Visualization Code?

### ISSUE THREAD

**Issue by zwx8981** [chihyaoma/selfmonitoring-agent#8]
Hi, would you mind sharing your complete visualization code? I think the figures in your paper look very nice :)

https://github.com/chihyaoma/selfmonitoring-agent/blob/39667f27864e992771f49c524052dc666d62fe84/scripts/panoramic_matterport.m#L58

**Comment by winnechan** [comment]
Have anyone solved this problem?

**Comment by winnechan** [comment]
Has anyone solved this problem?
